apps/article/urls.py
# _*_ coding: utf-8 _*_
__date__ = '2019/9/17 22:58'

from django.urls import path
from article.views import ArticleDetailView, ArchivesView


app_name = '[article]'
urlpatterns = [
    path('detail/<int:article_id>', ArticleDetailView.as_view(), name='detail'),
    # 归档
    path('', ArchivesView.as_view(), name='arch_all'),
]

blog/urls.py
from django.urls import path, include, re_path
import xadmin
from django.views.static import serve

from blog.settings import MEDIA_ROOT, STATIC_ROOT
from article.views import IndexView
from user.views import page_not_found, pag_error

urlpatterns = [
    path('xadmin/', xadmin.site.urls),
    # 首页
    path('', IndexView.as_view(), name='index'),
    path('user/', include('user.urls', namespace='user')),
    path('article/', include('article.urls', namespace='article')),
    # 归档
    path('archives/', include('article.urls', namespace='archives')),

    # ueditor
    path('ueditor/', include('DjangoUeditor.urls')),

    # 配置media路径，使网页的图片能从后台输出显示出来
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}, name='media'),
    # setting中设置 debug=False后，配置路径使静态文件能加载
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': STATIC_ROOT}, name='static'),
]

# 404页面配置
handler404 = page_not_found
# 全局500页面配置
handler500 = pag_error

tools/DjangoUeditor3-master/DUSite/urls.py
#coding:utf-8
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
import settings
from django.contrib import admin
from TestApp.views import  TestUEditorModel,ajaxcmd,TestUEditor

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'DUSite.views.home', name='home'),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ueditor/',include('DjangoUeditor.urls')),
    url(r'^test/$',TestUEditorModel),
    url(r'^test2/$',TestUEditor),
    url(r'^ajaxcmd/$',ajaxcmd)

)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT }),
        url(r'^static/(?P<path>.*)$','django.views.static.serve',{'document_root':settings.STATIC_ROOT}),
        url(r'^(?P<path>.*)$','django.views.static.serve',{'document_root':settings.STATIC_ROOT}),
    )

tools/DjangoUeditor3-master/DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

apps/article/models.py
from datetime import datetime

from django.db import models

from user.models import UserProfile
from DjangoUeditor.models import UEditorField
# Create your models here.


class Article(models.Model):
    author = models.ForeignKey(UserProfile, on_delete=models.CASCADE, verbose_name='作者')
    title = models.CharField(max_length=100, verbose_name='标题')
    introduce = models.CharField(max_length=100, null=True, blank=True, verbose_name='简介')
    # content = models.CharField(max_length=200, verbose_name='内容')
    content = UEditorField(verbose_name='内容', width=700, height=300, imagePath="article/ueditor/img/%(basename)s_%(date)s.%(extname)s",
                           filePath="article/ueditor/file/", upload_settings={"imageMaxSize": 1204000}, default='')
    type = models.CharField(max_length=2, choices=(('ht', '后台'), ('qd', '前端'), ('qt', '其他')), verbose_name='文章类型')
    image = models.ImageField(upload_to='article/%Y/%m', max_length=100, null=True, blank=True, verbose_name='封面图')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='发布时间')
    click_num = models.IntegerField(default=0, verbose_name='点击数')

    class Meta:
        verbose_name = '文章'
        # 不加plural会使后台页面的导航名带一个字母's'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.title


class Tag(models.Model):
    tag = models.CharField(max_length=30, verbose_name='标签')
    article = models.ManyToManyField(Article, through='ArticleTag')

    class Meta:
        verbose_name = '标签'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.tag


class ArticleTag(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, verbose_name='文章')
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE, verbose_name='标签')

    class Meta:
        verbose_name = '文章标签'
        verbose_name_plural = verbose_name

templates/archives.html
{% extends 'index.html' %}

{% block content %}
<div class="col-md-9">
    <div class="scroll-box" data-spy="scroll" data-target="#myScrollspy" data-offset="10">
        <h2 id="2019">2019</h2>
        {% for article in all_article %}
        <div class="panel panel-default">
            <div class="panel-body">
                <h4><a href="{% url 'article:detail' article.id %}">{{ article.title }}</a></h4>
                <p><time id="{{ article.add_time|date:'n' }}">{{ article.add_time|date:'Y年m月d日' }}</time> by <a href="#">{{ article.author.username }}</a></p>
                <p>{{ article.introduce }}</p>
            </div>
        </div><!-- 文章列表 -->
        {% endfor %}
    </div>
</div>
<div class="col-md-3">
    <nav id="myScrollspy">
        <ul class="nav nav-stacked">
            <li role="presentation" class="active">
                <a href="#2019">2019年</a>
                <ul class="nav">
                    {% for archives in archives_list %}
                    <li role="presentation">
                        <a href="#{{ archives.1 }}">{{ archives.1 }}月</a>
                    </li>
                    {% endfor %}
                </ul>
            </li>
        </ul>
    </nav>
</div>
{% endblock %}

{% block custom_css %}
<style>
</style>
{% endblock %}

{% block custom_js %}
<script>$('body').scrollspy({ target: '#myScrollspy' })</script>
{% endblock %}

templates/article_detail.html
{% extends 'index.html' %}

{% block content %}
<div class="col-md-9">
    <ol class="breadcrumb">
        <li><a href="{% url 'index' %}">首页</a></li>
        <li class="active">文章详情</li>
    </ol>

    <div class="article-box">
        <h3>{{ article.title }}</h3>
        <p>日期：<time>{{ article.add_time }}</time> 作者：<a href="#">{{ article.author.username }}</a> 类型：{{ article.get_type_display }}</p>
        <hr>
        <div>
            {% autoescape off %}
            {{ article.content }}
            {% endautoescape %}
        </div>
    </div>

    <nav aria-label="Page navigation">
        <ul class="pager">
            <li class="previous"><a href="{% url 'article:detail' previous_article.id %}"><span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span> 上一篇：{{ previous_article.title }}</a></li>
            <li class="next"><a href="{% url 'article:detail' next_article.id %}">{{ next_article.title }}：下一篇 <span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span></a></li>
        </ul>
    </nav>
</div>

<div class="col-md-3">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">最新文章</h3>
        </div>

        <div class="panel-body">
            <div><time>sssss</time></div>
            <a href="#">aaaaa</a>
            <p><a href="">ccccc</a></p>
        </div>
        <div class="panel-body">
            <div><time>sssss</time></div>
            <a href="#">aaaaa</a>
            <p><a href="">ccccc</a></p>
        </div>
        <div class="panel-body">
            <div><time>sssss</time></div>
            <a href="#">aaaaa</a>
            <p><a href="">ccccc</a></p>
        </div>
    </div><!-- panel-default 最新文章 -->
</div>
{% endblock %}

{% block custom_js %}
<script type="text/javascript">
var height = $('.article-box').height()
if(height < 200){
    $('.docs-footer').css('paddingBottom', 100);
}
</script>
{% endblock %}

templates/index.html
<!DOCTYPE html>
<html lang="zh-CN">
{% load staticfiles %}
{% load to_str %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>{% block title %}海涵的个人网站{% endblock %}</title>
    <link rel="icon" href="{% static 'images/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    {% block custom_css %}{% endblock %}
</head>

<body>
<!-- Header
 ================================================== -->
<header class="navbar navbar-static-top" id="top">
    <div class="container">
        <div class="navbar-header">
            <a href="{% url 'index' %}" class="navbar-brand">SeaSail</a>
        </div>
        <nav id="bs-navbar" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li {% if cur_page == "index" %}class="active"{% endif %}><a href="{% url 'index' %}">主页</a></li>
                <li {% if cur_page == "archives" %}class="active"{% endif %}><a href="{% url 'archives:arch_all' %}">归档</a></li>
                <li><a href="#">分类</a></li>
                <li><a href="#">简介</a></li>
            </ul>
            <form class="navbar-form navbar-right">
                <div class="input-group">
                    <input id="SearchVal" type="text" class="form-control" placeholder="搜索标题 / 内容">
                    <span class="input-group-btn">
                        <button id="SearchBtn" class="btn btn-default" type="button">
                            <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                        </button>
                    </span>
                </div><!-- /input-group -->
            </form>
        </nav>
    </div>
</header>

<!-- Container
 ================================================== -->
<div class="container">
    {% block content %}
    <div class="col-md-3">
        <div class="row">
            <div class="personal-box">
                <img src="{{ MEDIA_URL }}{{ user.image }}" width="140" class="img-circle">
                <h3>{{ user.username }}</h3>
                <h6>Web Apprentice</h6>
                <div class="category-box">
                    <div>
                        <p>文章</p>
                        <p>{{ user.get_article_num }}</p>
                    </div>
                    <div>
                        <p>分类</p>
                        <p>3</p>
                    </div>
                    <div>
                        <p>文章</p>
                        <p>42</p>
                    </div>
                </div>
                <div class="category-box">
                    <a tabindex="0" class="btn btn-lg" role="button" data-toggle="popover" title="所在地区" data-content="广东广州天河区">
                        <span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span>
                    </a>
                    <a tabindex="0" class="btn btn-lg" role="button" data-toggle="popover" title="我的邮箱" data-content="2943546196@qq.com">
                        <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
                    </a>
                    <a tabindex="0" class="btn btn-lg" role="button" data-toggle="popover" title="微信二维码" data-html="true" data-content="<img src='{% static 'images/vx_code.jpg' %}' width='100px'>">
                        <span class="glyphicon glyphicon-qrcode" aria-hidden="true"></span>
                    </a>
                </div>
            </div><!-- personal-box -->
        </div><!-- row -->

        <div>
            <ol class="list-group">
                <li class="list-group-item"><h3 class="panel-title">友情链接</h3></li>
                <li class="list-group-item">
                    <a href="https://glyphicons.com/">Glyphicons 字体图标</a>
                </li>
            </ol>
        </div><!-- 友情链接 -->
    </div><!-- 左侧列 -->

    <div class="col-md-6">
        {% for article in page_art %}
        <div class="panel panel-default">
            <div class="panel-body">
                <h4><a href="{% url 'article:detail' article.id %}">{{ article.title }}</a></h4>
                <p><time>{{ article.add_time|date:'Y年m月d日' }}</time> by <a href="#">{{ article.author.username }}</a></p>
                <p>
                    <span class="glyphicon glyphicon-tag" aria-hidden="true"></span>
                    {% for tag in article.tag_set.all %}
                    <span class="badge">{{ tag }}</span>
                    {% endfor %}
                </p>
            </div>
        </div><!-- 文章列表 -->
        {% endfor %}

        <div class="col-md-6 col-md-offset-3">
            <nav aria-label="Page navigation">
                <ul class="pagination">
                    {% if page_art.has_previous %}
                    <li><a href="?page={{ page_art.previous_page_number }}" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>
                    {% else %}
                    <li class="disabled"><span href="#" aria-label="Previous"><span aria-hidden="true">&laquo;</span></span></li>
                    {% endif %}

                    {% for pgm in page_art.paginator.page_range %}
                        {% if page_art.number == pgm %}
                            <li class="active"><span href="?page={{ pgm }}">{{ pgm }}</span></li>
                        {% else %}
                            <li><a href="?page={{ pgm }}">{{ pgm }}</a></li>
                        {% endif %}
                    {% endfor %}

                    {% if page_art.has_next %}
                    <li><a href="?page={{ page_art.next_page_number }}" aria-label="Next"><span aria-hidden="true">&raquo;</span></a></li>
                    {% else %}
                    <li class="disabled"><span href="#" aria-label="Next"><span aria-hidden="true">&raquo;</span></span></li>
                    {% endif %}
                </ul>
            </nav>
        </div><!-- col-md-5 分页 -->
    </div><!-- blog-main -->

    <div class="col-md-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">最新文章</h3>
            </div>
            {% for article in new_article %}
            <div class="panel-body">
                <div><time>{{ article.add_time|date:'Y-m-d' }}</time></div>
                <a href="{% url 'article:detail' article.id %}">{{ article.title }}</a>
                <p><a href="">{{ article.get_type_display }}</a></p>
            </div>
            {% endfor %}
        </div><!-- panel-default 最新文章 -->

        <div>
            <ol class="list-group">
                <li class="list-group-item"><h3 class="panel-title">归档</h3></li>
                {% for archives in archives_list %}
                <li class="list-group-item">
                    <span class="badge">{{ archives.2 }}</span>
                    <a href="{% url 'archives:arch_all' %}">{{ archives.1|to_str }}月{{ archives.0 }}年</a>
                </li>
                {% endfor %}
            </ol>
        </div><!-- 归档 -->

    </div><!-- 右侧列 -->
    {% endblock %}
</div><!-- container -->

<!-- Footer
 ================================================== -->
<div class="docs-footer">
    <div class="container">
        <div>
            <h6>海涵的个人博客网站</h6>
            <h6>Frame by <a href="https://www.djangoproject.com/">Django</a> and <a href="https://v3.bootcss.com/">Bootstrap</a>.</h6>
        </div>
    </div>
</div>



<script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.js' %}"></script>
<script type="text/javascript">
$('#SearchBtn').on('click', function(){
    var request_url = '';
    var key_words = $('#SearchVal').val();
    if(key_words==''){return}
    else{request_url='?keywords='+key_words}
    window.location.href = request_url
});
</script>
{% block custom_js %}
<script>
$('[data-toggle="popover"]').popover({
    placement: 'bottom',
    trigger: 'focus'
 });
</script>
{% endblock %}
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="container">

      <form class="form-signin">
        <h2 class="form-signin-heading">Please sign in</h2>
        <label for="inputEmail" class="sr-only">Email address</label>
        <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required="" autofocus="">
        <label for="inputPassword" class="sr-only">Password</label>
        <input type="password" id="inputPassword" class="form-control" placeholder="Password" required="">
        <div class="checkbox">
          <label>
            <input type="checkbox" value="remember-me"> Remember me
          </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
      </form>

    </div>
</body>
</html>

templates/test.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
  <title>Document</title>
  <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"> -->
   <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/4.3.1/css/bootstrap.min.css">
  <script src="https://cdn.staticfile.org/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://cdn.staticfile.org/popper.js/1.15.0/umd/popper.min.js"></script>
  <script src="https://cdn.staticfile.org/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>
  <style>
  body {
      position: relative;
  }
  ul.nav-pills {
      top: 20px;
      position: fixed;
  }
  div.col-8 div {
      height: 500px;
  }
  </style>
</head>
<body data-spy="scroll" data-target="#myScrollspy" data-offset="1">
<div class="container-fluid">
  <div class="row">
    <nav class="col-sm-3 col-4" id="myScrollspy">
      <ul class="nav nav-pills">
        <li class="nav-item">
          <a class="nav-link active" href="#section1">Section 1</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#section2">Section 2</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#section3">Section 3</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#">Section 4</a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="#section41">Link 1</a>
            <a class="dropdown-item" href="#section42">Link 2</a>
          </div>
        </li>
      </ul>
    </nav>
    <div class="col-sm-9 col-8">
      <div id="section1" class="bg-success">
        <h1>Section 1</h1>
        <p>Try to scroll this section and look at the navigation list while scrolling!</p>
      </div>
      <div id="section2" class="bg-warning">
        <h1>Section 2</h1>
        <p>Try to scroll this section and look at the navigation list while scrolling!</p>
      </div>
      <div id="section3" class="bg-secondary">
        <h1>Section 3</h1>
        <p>Try to scroll this section and look at the navigation list while scrolling!</p>
      </div>
      <div id="section41" class="bg-danger">
        <h1>Section 4-1</h1>
        <p>Try to scroll this section and look at the navigation list while scrolling!</p>
      </div>
      <div id="section42" class="bg-info">
        <h1>Section 4-2</h1>
        <p>Try to scroll this section and look at the navigation list while scrolling!</p>
      </div>
    </div>
  </div>
</div>


<script>
  $('[data-spy="scroll"]').scrollspy({ target: '#myScrollspy' })
</script>
</body>
</html>

templates/user_info.html
{% extends 'index.html' %}

{% block content %}
<span>user info page</span>
{% endblock %}